### PR TITLE
Add KelvinPerMinute to TemperatureChangeRateUnit

### PR DESCRIPTION
**Pull request by andrewmeservy**
- Add KelvinPerMinute to TemperatureChangeRateUnit
- Add "pause" at end of generate-code.bat so the cmd window does not close immediately, allowing devs to inspect any errors that may have occurred during the command execution.

### CODE REVIEW

**Comment by lipchev** [comment]
@angularsen I don't believe this has been carried over to `v6`, do you have something planned for it?

**Comment by andrewmeservy** [comment]
would def appreciate this being included in future versions, and really appreciate David-HH-Dev fixing the conversion calculation :)

**Comment by angularsen** [comment]
@lipchev It will eventually be merged in along with everything else from master to v6, when I have enough time and energy to deal with all the merge conflits 😄

**Comment by angularsen** [comment]
If anyone is eager to get it into v6 sooner, you can do a separate PR targeting `release/v6` branch.

**Comment by lipchev** [comment]
I think it's only this and the #1452 that are out of sync (not counting the #1467 )

**Comment by angularsen** [comment]
Merged into V6 branch, nuget should be out shortly.

[Release UnitsNet/6.0.0-pre013 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F6.0.0-pre013)

**Pull request merged**
