### PR TITLE
Get unit infos for

### PR DESCRIPTION
**Pull request by tmilnthorp**
@angularsen to stop the exceptions (default to first match) when constructing a quantity for a unit system.

Should we maybe give a bool flag to allow an exception? Or somehow indicate there may be more than one match.

### CODE REVIEW

**Comment by tmilnthorp** [comment]
Maybe a From/TryFrom that returns an IEnumerable would be better?

**Comment by angularsen** [comment]
> Maybe a From/TryFrom that returns an IEnumerable would be better?

I think that sounds better, yes. It clearly communicates that multiple matches should be expected.

**Comment by tmilnthorp** [comment]
On each of the quantity classes, in addition to the UnitSystem constructor. I think this is still better than the exception though. I'll change the documentation before I merge to note the fact it returns the first match.

**Comment by tmilnthorp** [comment]
Doc updated. I'll do the From/TryFrom in another PR.

**Comment by angularsen** [comment]
[Release UnitsNet/4.17.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.17.0)

**Pull request merged**
