### PR TITLE
Adding imperial units for thermal conductivity

### PR DESCRIPTION
**Pull request by tmilnthorp**

### CODE REVIEW

**Comment by angularsen** [comment]
Huh, that's weird what the test is failing on in the appveyor build. I'll have to take a look tomorrow unless you figure it out in between. I've queued another build to see if it is a flaky test.

**Comment by gojanpaolo** [comment]
I always get that failing test on my machine.

**Comment by angularsen** [comment]
@gojanpaolo Probably a racing condition when running tests in parallel, we do have some issues with tests that manipulate some static fields to verify default behavior of number formatting and abbreviation language. Solution is to ensure those tests are not run in parallel with any other tests.

**Comment by angularsen** [comment]
Sorry a bit late to respond, busy days.. 
This looks good, thanks!

**Comment by angularsen** [comment]
Nuget 3.98 on the way out.

**Comment by angularsen** [comment]
Created issue on flaky test: https://github.com/angularsen/UnitsNet/issues/436

**Pull request merged**
