### PR TITLE
Remove internal parse methods

### PR DESCRIPTION
**Pull request by angularsen**
Based on #520 so merge that first.
Parse/TryParseInternal and Parse/TryParseUnitInternal methods are redundant since the same logic is already in QuantityParser.
Also use UnitParser with the given UnitAbbreviationsCache instead of external unit parsing code via delegates.

This saves method declarations for all our 80 quantities, reduces binary size and helps keep things more DRY.

### CODE REVIEW

**Comment by angularsen** [comment]
I'm fixing merge errors now.

**Comment by angularsen** [comment]
Rebased.

**Comment by tmilnthorp** [comment]
Just one tests fails expecting an exception I don't see. I think we may have removed it during refactoring. Intentional or accidental?

**Comment by angularsen** [comment]
Test caught a flaw in the implementation actually, fixed now.

**Pull request merged**
