### PR TITLE
Turn on nullable ref types for extensions

### PR DESCRIPTION
**Pull request by tmilnthorp**
More work for #688

### CODE REVIEW

**Comment by angularsen** [comment]
Love it! A lot of great activity from you lately 😀 
Care to share your trick to squeeze in time in-between family life? 😆

**Comment by tmilnthorp** [comment]
Daycare opened back up here in the States 😄

**Comment by angularsen** [comment]
LOL! 😂 Same here, things definitely eased up when schools and kindergarden opened back up again.

**Comment by angularsen** [comment]
[Release UnitsNet/4.62.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.62.0)

**Pull request merged**
