### PR TITLE
Update .NET nanoFramework NuGets

### PR DESCRIPTION
**Pull request by nfbot**
Automated update from @nfbot.

### CODE REVIEW

**Comment by josesimoes** [comment]
@angularsen happy new year!! 🥳 
Please look into this one when you can. "Just" updating new releases for mscorlib and Sys.Math.

**Comment by angularsen** [comment]
Thanks! Happy new year to you as well, I have a feeling it will be a good one.

I love this bot! Nuget should be out shortly. 

[Release UnitsNet/5.0.0-rc009 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.0.0-rc009)

**Comment by josesimoes** [comment]
@angularsen any chance we can have these .NET nanoFramework releases with v4.xx? 
The fact that the new ones are using "preview" versioning it's  messing  completely our update tool...

**Comment by angularsen** [comment]
@josesimoes Sure, we just need to merge these changes into both `master` and `release/v4` until the nuget is no longer prerelease. No ETA on that yet, just holding the door open for any last minute breaking changes.

I cherry picked this PR into #1179, then regenerated the code there.

**Pull request merged**
