### PR TITLE
Add Volume.CubicHectometer

### PR DESCRIPTION
**Pull request by cpmoliveira**
It is a unit very used in hydrology.

### CODE REVIEW

**Comment by angularsen** [comment]
Hi, thanks for contributing. You're missing the generated code, just run `generate-code.bat`, commit and push that to the branch.

Please see https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for detailed instructions.

**Comment by tmilnthorp** [comment]
Should new units be added to the end of json files? I know we don't preserve enum ordering (it's alphabetical). But we could and it would allow persistence of enum values.

**Comment by angularsen** [comment]
Fair question, I haven't really paid much attention to it so far. I guess I would favor keeping it alphabetically, but I have no strong opinion on this.

**Comment by cpmoliveira** [comment]
> Hi, thanks for contributing. You're missing the generated code, just run `generate-code.bat`, commit and push that to the branch.
> 
> Please see https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for detailed instructions.

I'm sorry, but I'm new here. Thanks for the correction and inform the instructions.
Great job!

**Comment by angularsen** [comment]
@cpmoliveira No problem, also you can keep this pull request. No need to close it, just push new commits to the same branch `path-1`.

**Comment by cpmoliveira** [comment]
Moved to #638

**Pull request closed without merging**
