### PR TITLE
Split wrc

### PR DESCRIPTION
**Pull request by tmilnthorp**
More work towards #409. Creating code generator script for .NET-only code. Using existing script to generate "common" code for both .NET and WRC. Removing #if WINDOWS_UWP from Value property in Common code and moving each to their separate .NET and WCR code generators.

### CODE REVIEW

**Comment by tmilnthorp** [comment]
This is more baby steps FYI. There's a lot more code to pull into the separate implementations for .NET and WRC. It is already a lot of changed files so I didn't want to go too far immediately.

**Comment by tmilnthorp** [comment]
Ultimately I'd like to move the scripts around to their appropriate folders/projects also. Possibly even move the common script out of the UnitsNet folder and into a "Common" folder (Common\Scripts).

I'd also like to move the generated code directories around a bit to split Common/.NET/WRC into their appropriate folders.

Common\GeneratedCode.
UnitsNet\GeneratedCode
WindowsRuntimeComponent\GeneratedCode

etc.

Trying to do this slowly since it will be large changes!

**Comment by angularsen** [comment]
Consider naming it UnitsNet.Common to distinguish it from say json serialization code.

**Comment by angularsen** [comment]
Awesome, looks good. The phone 📱 struggles with these huge diffs though 😁

**Pull request merged**
