### PR TITLE
Use pattern matching for switch statements

### PR DESCRIPTION
**Pull request by tmilnthorp**
Slightly more concise IMHO. Thoughts?

### CODE REVIEW

**Comment by angularsen** [comment]
Absolutely, I love the new c# stuff ❤️

**Comment by tmilnthorp** [comment]
:-O It didn't build yet.

How do I build NanoFramework btw?

**Comment by angularsen** [comment]
Oh right :D Sorry!
By the way, you can just go ahead and merge minor PRs like this yourself, I'll still keep an eye on things anyways.

**Comment by angularsen** [comment]
[Release UnitsNet/4.120.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.120.0)

**Pull request merged**
