### PR TITLE
Added Megameter (1e+6 meters)

### PR DESCRIPTION
**Pull request by Mando501**
Megameter is a useful intermediate unit between kilometer and light second

Use cases tend towards astronomical such as satellite orbits

### CODE REVIEW

**Comment by tmilnthorp** [comment]
@Mando501 this can be added to the existing Prefixes for Meter

**Comment by Mando501** [comment]
> 

I must have missed Prefixes. I'll take a look, thanks.

**Comment by Mando501** [comment]
Went back and removed the entry in Length.json and added Mega to the Prefixes for Meter.

I can't believe I missed that prefixes were a thing - that makes so much more sense 😂

**Comment by angularsen** [comment]
Thanks! Nuget is on the way.

[Release UnitsNet/5.4.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.4.0)

**Pull request merged**
