### PR TITLE
Add Micro and Milli prefixes to Frequency

### PR DESCRIPTION
**Pull request by Muximize**
Adds Micro and Milli prefixes to Frequency. Is this all that is needed?

### CODE REVIEW

**Comment by angularsen** [comment]
@Muximize Close, just run `generate-code.bat` and push those changes too 👍

**Comment by angularsen** [comment]
@Muximize Sorry, I forgot, you then also need to implement two test cases in `FrequencyTests`.
There is a compilation error there now you must fix.

```
D:\a\1\s\UnitsNet.Tests\CustomCode\FrequencyTests.cs(8,18): error CS0534: 'FrequencyTests' does not implement inherited abstract member 'FrequencyTestsBase.MicrohertzInOneHertz.get' [D:\a\1\s\UnitsNet.Tests\UnitsNet.Tests.csproj::TargetFramework=net7.0]
D:\a\1\s\UnitsNet.Tests\CustomCode\FrequencyTests.cs(8,18): error CS0534: 'FrequencyTests' does not implement inherited abstract member 'FrequencyTestsBase.MillihertzInOneHertz.get' [D:\a\1\s\UnitsNet.Tests\UnitsNet.Tests.csproj::TargetFramework=net7.0]
D:\a\1\s\UnitsNet.Tests\CustomCode\FrequencyTests.cs(8,18): error CS0534: 'FrequencyTests' does not implement inherited abstract member 'FrequencyTestsBase.MillihertzInOneHertz.get' [D:\a\1\s\UnitsNet.Tests\UnitsNet.Tests.csproj::TargetFramework=net48]
D:\a\1\s\UnitsNet.Tests\CustomCode\FrequencyTests.cs(8,18): error CS0534: 'FrequencyTests' does not implement inherited abstract member 'FrequencyTestsBase.MicrohertzInOneHertz.get' [D:\a\1\s\UnitsNet.Tests\UnitsNet.Tests.csproj::TargetFramework=net48]
```

https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=281&view=logs&jobId=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=9d4476d9-f6e2-5f97-1036-4124d48c41e1


The steps are outlined in the wiki:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#4-fix-generated-test-stubs-to-resolve-compile-errors-tests

**Comment by Muximize** [comment]
Ah, my bad, I literally did what you said without building or testing 🙈

**Comment by angularsen** [comment]
Great! Nuget should be out shortly. 5.0 is still in prerelease, mostly to leave room for some minor last minute breaking changes, but it's stable and will probably leave prerelease in February or so.

[Release UnitsNet/5.0.0-rc011 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.0.0-rc011)

**Comment by Muximize** [comment]
Great, thank you!

**Pull request merged**
