### PR TITLE
Adding JoulePerSquareCentimeter and KiloJoulesPerSquareMeter

### PR DESCRIPTION
**Pull request by ngeslin**

### CODE REVIEW

**Comment by angularsen** [comment]
Looks good to me!

**Comment by angularsen** [comment]
[Release UnitsNet/4.9.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.9.0)

**Comment by tmilnthorp** [comment]
Just a quick note: when we add new units like this we should re-gen WRC. Can we do this as part of the build or would we have to intervene before merging?

**Comment by angularsen** [comment]
1. It's always regenerated in AppVeyor builds (it runs build-with-wrc.bat)
2. Both .NET and WRC source code is regenerated with `generate-code.bat`

**Comment by angularsen** [comment]
#610

**Comment by tmilnthorp** [comment]
Yup :) and the changes show up in diffs when adding new features

**Pull request merged**
