### PR TITLE
Adding benchmark project

### PR DESCRIPTION
**Pull request by tmilnthorp**
Wanted to draft a first shot at #623

### CODE REVIEW

**Comment by tmilnthorp** [comment]
Pretty cool! My results:

``` ini

BenchmarkDotNet=v0.11.4, OS=Windows 10.0.14393.2791 (1607/AnniversaryUpdate/Redstone1)
Intel Xeon CPU E5-2687W v3 3.10GHz, 2 CPU, 20 logical and 20 physical cores
Frequency=3020348 Hz, Resolution=331.0877 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3324.0
  DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3324.0


```
|                 Method |          Mean |       Error |      StdDev |
|----------------------- |--------------:|------------:|------------:|
|            Constructor |     13.260 ns |   0.1336 ns |   0.1250 ns |
|             FromMethod |     46.056 ns |   0.0133 ns |   0.0111 ns |
|             ToProperty |      6.828 ns |   0.0109 ns |   0.0102 ns |
|                     As |      6.835 ns |   0.0144 ns |   0.0112 ns |
|                 ToUnit |     20.030 ns |   0.0820 ns |   0.0685 ns |
|           ToStringTest |  1,917.247 ns |  13.4056 ns |  11.1943 ns |
|                  Parse | 42,953.469 ns | 298.2893 ns | 279.0200 ns |
|          TryParseValid | 42,405.649 ns |  75.9599 ns |  71.0530 ns |
|        TryParseInvalid | 43,404.853 ns |  70.1466 ns |  65.6152 ns |
|           QuantityFrom |    118.089 ns |   0.7960 ns |   0.6647 ns |
|           IQuantity_As |     11.941 ns |   0.0265 ns |   0.0207 ns |
|       IQuantity_ToUnit |     29.974 ns |   0.0371 ns |   0.0310 ns |
| IQuantity_ToStringTest |  2,096.857 ns |   5.5514 ns |   4.9212 ns |

**Comment by tmilnthorp** [comment]
I switched over everything to class and here are the results on the same machine:
``` ini

BenchmarkDotNet=v0.11.4, OS=Windows 10.0.14393.2791 (1607/AnniversaryUpdate/Redstone1)
Intel Xeon CPU E5-2687W v3 3.10GHz, 2 CPU, 20 logical and 20 physical cores
Frequency=3020348 Hz, Resolution=331.0877 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3324.0
  DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3324.0


```
|                 Method |          Mean |       Error |      StdDev |        Median | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------------------- |--------------:|------------:|------------:|--------------:|------------:|------------:|------------:|--------------------:|
|            Constructor |     13.667 ns |   0.0697 ns |   0.0618 ns |     13.659 ns |      0.0046 |           - |           - |                24 B |
|             FromMethod |     48.528 ns |   0.1178 ns |   0.1102 ns |     48.500 ns |      0.0045 |           - |           - |                24 B |
|             ToProperty |      6.768 ns |   0.0223 ns |   0.0208 ns |      6.768 ns |           - |           - |           - |                   - |
|                     As |      6.765 ns |   0.0171 ns |   0.0152 ns |      6.765 ns |           - |           - |           - |                   - |
|                 ToUnit |     22.419 ns |   0.0531 ns |   0.0415 ns |     22.414 ns |      0.0046 |           - |           - |                24 B |
|           ToStringTest |  1,852.535 ns |   4.2119 ns |   3.5171 ns |  1,852.616 ns |      0.1259 |           - |           - |               664 B |
|                  Parse | 42,695.622 ns | 139.4434 ns | 123.6129 ns | 42,664.711 ns |      4.5776 |      0.0610 |           - |             24209 B |
|          TryParseValid | 42,701.804 ns | 390.5792 ns | 365.3481 ns | 42,550.505 ns |      4.5776 |      0.0610 |           - |             24197 B |
|        TryParseInvalid | 43,811.580 ns | 236.0834 ns | 220.8326 ns | 43,769.209 ns |      4.5166 |      0.0610 |           - |             23868 B |
|           QuantityFrom |    117.510 ns |   0.2298 ns |   0.2150 ns |    117.483 ns |      0.0067 |           - |           - |                36 B |
|           IQuantity_As |     56.601 ns |  50.4925 ns |  58.1473 ns |     30.088 ns |           - |           - |           - |                12 B |
|       IQuantity_ToUnit |     28.047 ns |   0.0989 ns |   0.0925 ns |     28.054 ns |      0.0069 |           - |           - |                36 B |
| IQuantity_ToStringTest |  1,913.900 ns |  33.9251 ns |  31.7336 ns |  1,899.572 ns |      0.1259 |           - |           - |               664 B |

**Comment by angularsen** [comment]
Very neat, so from a first glance, looks pretty darn similar to me?

**Comment by tmilnthorp** [comment]
Nothing too horrible. IQuantity_As is the only standout. 

That said, these are only testing existing created quantities (minus the constructor). I will add more tests that actually create and then do something with it. I think you might see differences there (due to boxing and unboxing or lack there of).

**Comment by angularsen** [comment]
I'm inclined to merge this @tmilnthorp , we can always improve in further PRs. It's easier to test it locally and play with it when merged. Agree?

**Comment by tmilnthorp** [comment]
Sounds good to me!

**Comment by angularsen** [comment]
[Release UnitsNet/4.30.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.30.0)

**Pull request merged**
