### PR TITLE
Add Russian frequency units

### PR DESCRIPTION
**Pull request by Dblm0**
#766

Some Russian frequency units translations have been added, except for `cpm` `cph` and `bpm`

### CODE REVIEW

**Comment by angularsen** [comment]
I'll have to trust your translations, but could you also please run `generate-code.bat` and push the updated source code?

**Comment by Dblm0** [comment]
> 
> 
> I'll have to trust your translations, but could you also please run `generate-code.bat` and push the updated source code?

done

**Comment by angularsen** [comment]
Sorry for the slow response on my part, looks good thanks!

**Comment by angularsen** [comment]
[Release UnitsNet/4.74.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.74.0)

**Pull request merged**
