### PR TITLE
Generic math for UnitsNet in .NET 7

### PR DESCRIPTION
**Pull request by AndreasLeeb**
Hi,

since it's already been quite some time since #984 and as #1129 shows that the topic is of interest, I also gave it a shot.
So far, it's been a surprisingly minimally invasive undertaking.

Changes so far:
- build UnitsNet in .NET 7 as well with very limited conditional compilation for the generic math interfaces
- extended IQuantity interface hierarchy to support generic math (as the TSelf parameter for CRT pattern, and the underlying value type are needed)
- automatically generated operator overloads and parsing methods are covered by the respective generic math interfaces

Still to do:
- also cover the manually added operator overloads in the *.extra.cs files with generic math interfaces
- also implement ISpanParsable, which will need some work, especially in the QuantityParser
- maybe for symmetry reasons also overload the unary + operator and implement IUnaryPlusOperators. However, I'm unsure because it's a pretty useless operator
- resolve nullable reference types chaos: since multi-targeting with net7.0 even when disabling the nullability in the csproj I kept getting tons of errors for both netstandard2.0 and net7.0 builds, so for now I've disabled the respective warnings. We should fully use the nullable reference types feature in the whole code base also for .netstandard2.0 to solve this tangle

Pain points:
- multiplication with one operand of Quantity type and one operand of double/decimal type only supported with Quantity being the first parameter (when adding the commutative case, I get errors 
grafik
- I suspect we'll run into the same issues with some custom overloads involving commutative multiplication with different quantity types

### CODE REVIEW

**Comment by angularsen** [comment]
Awesome! I will have to take a closer look later.

**Comment by angularsen** [comment]
I fixed nullable annotations in #1175 and added some initial extension methods `Sum` and `Average` to test out the new generic math interfaces in practice.

Some changes made to the PR:
- Merge in latest master, with nullable fix
- Re-enable nullable, remove mute of warnings
- Tweak `IQuantity` constraints for generic math, specifically the `IDivisionOperators` had to be changed to support dividing by a number for `Average()`. Details in ed27b33fa626296a577a65805e273249851c0919.
- The extension methods were written so we don't have to specify the generic type arguments, in particular supporting `Average` for both `double` and `decimal` quantities required two separate extension method classes to keep the same method name. I tried adding both value types to the generic math interface list, but that resulted in ambiguous method errors.


Please review my commits and take a look whether we should expand on the extension methods or make other tweaks, but I think this is more or less ready to go. 

There are definitely some paper cuts with regards to having units in the mix, such as addition picking the left hand side unit so my initial attempt at Average() resulted in the base unit instead of the unit in the collection. We'll just have to test this out more and get a better feel for it, but it does seem to kind of work.

**Comment by AndreasLeeb** [comment]
Looks good, I think 👍 

Regarding the operators in the *.extra.cs files, that could be tackled easily by describing the dependencies (operations) between different quantities in the quantity JSON files, and then the operator overloads and the generic math interfaces for the quantity structs could also be automatically generated. But that's a topic for another time 😄

**Comment by angularsen** [comment]
Thanks for the great work! The nuget should be out to play with shortly.

[Release UnitsNet/5.0.0-rc008 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.0.0-rc008)

**Pull request merged**
