### PR TITLE
Set up Azure Pipelines

### PR DESCRIPTION
**Pull request by angularsen**

### CODE REVIEW

**Comment by angularsen** [comment]
@josesimoes I'm experimenting with moving the build over to DevOps, but am running into some unusual errors. You mentioned you had a setup for this at your place. Would you mind taking a look?

It is basically running `build.ps1` on `windows-latest`.

https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=145&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a

> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\NFProjectSystem.MDP.targets(779,5): error MSB4062: The "GenerateBinaryOutputTask" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll. Could not load file or assembly 'file:///C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\1\s\UnitsNet.NanoFramework\GeneratedCode\WarpingMomentOfInertia\WarpingMomentOfInertia.nfproj]

**Comment by josesimoes** [comment]
@angularsen wow!! That's a great move. 👏🏻 😉 

Yes, we have that on our pipelines. There's an AZDO Task that we maintain for taking care of this. 
I've made the changes in #1150.

**Comment by angularsen** [comment]
@josesimoes Sorry for nagging, but the NF install task now succeeds, but I'm still stuck with this error. Any ideas?

It seems the `init.ps1` script no longer installs NanoFramework extension at least, but the error remains the same:

> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\NFProjectSystem.MDP.targets(779,5): error MSB4062: The "GenerateBinaryOutputTask" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll. Could not load file or assembly 'file:///C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\1\s\UnitsNet.NanoFramework\GeneratedCode\Acceleration\Acceleration.nfproj]

https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=154&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a

**Comment by josesimoes** [comment]
@angularsen no nagging at all! 😄 
That's because of the need to use the x64 version of msbuild. Totally forgot about that. #1151 should fix it.

**Comment by angularsen** [comment]
@josesimoes Inching towards success 😅

> D:\a\1\s\UnitsNet.NanoFramework\GeneratedCode\Acceleration\Acceleration.nfproj : error MSB4057: The target "Build" does not exist in the project.

https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=158&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a

Now the AppVeyor build fails too, with the same. I assume the switch to `amd64` somehow fails this?
I tried removing the "Any CPU" change, to isolate the changes, but still getting the same error.

**Comment by angularsen** [comment]
Aha, didn't see your comment until now. Trying to merge that.

**Comment by josesimoes** [comment]
@angularsen BRAVO!!! 😁 👏👏👏
All 🟢 well done. let's have the AZDO badge on the readme. 😉

**Comment by angularsen** [comment]
@josesimoes Very nice! Thanks a lot for the help with the Nano build.

A comparison after merging to master:
- Azure Pipelines: 10 min 👏
- AppVeyor: 25 min

Just the build time improvement alone is a big boost!
The only missing part is nuget push, but other than that they're doing the same work.

**Comment by angularsen** [comment]
Ah no, I commented out Windows Runtime Component build, so maybe +1 minute or so on that. Running tests with coverage is the big slow thing in the build.

**Comment by josesimoes** [comment]
I hadn't compared the build times. Indeed that's impressive!! 😯 💯 
Happy to help!! That's the least I can do thank you for the awesome UnitsNet and how convenient that is to projects like ours. 😃

**Comment by josesimoes** [comment]
On the nuget push: what are you struggling with? Maybe I can help there too. We use that on our 999 libraries at nanoFramework. 
There is an AZDO task that takes care of that... but you're probably aware of that of course.

**Comment by angularsen** [comment]
It's just how to make it ignore 409 conflict when trying to push versions already published, or find a way to avoid pushing nugets unless the version is not already published.

From a quick google, it seems the built in task does not allow ignoring 409 conflict for external nuget sources (nuget.org), but it does support that for the internal nuget feed of DevOps.

So I will probably have to use the dotnet or nuget CLI to push them.

**Comment by angularsen** [comment]
https://stackoverflow.com/a/66021477/134761

**Comment by josesimoes** [comment]
That works for nuget.org too. We use that on our task. Look here
https://github.com/nanoframework/nf-tools/blob/27b7a711fe7dabcfdc8f9cb308d1cf5e007d2e7b/azure-pipelines-templates/class-lib-publish.yml#L99

**Comment by angularsen** [comment]
Weird, it absolutely fails my nuget push task and thus the job.
image


I also noticed that if I click "Settings" to open up the UI to edit a task, the option to ignore conflicts is available for "internal" feed, but hidden when switching to "external" feed.
So all things point to this not being supported.

image


image

**Comment by josesimoes** [comment]
We do have the continue on error option, so you might want to try adding that...

**Pull request merged**
