### PR TITLE
Use "kn" as default abbreviation for knots (ISO Standard)

### PR DESCRIPTION
**Pull request by gojanpaolo**
https://en.wikipedia.org/wiki/Knot_(unit)
> The ISO standard symbol for the knot is kn.

### CODE REVIEW

**Comment by angularsen** [comment]
I'll just merge it then @tmilnthorp, sounds good to me too. I don't consider this a breaking change, even if ToString() will change default abbreviation.

**Comment by angularsen** [comment]
Nuget 104 on its way out.

**Comment by tmilnthorp** [comment]
Unless you do a ToString followed by a Parse :)

**Comment by angularsen** [comment]
Parse should still handle it, since we didn't remove any abbrevs - only changed the order of priority.

**Pull request merged**
