### PR TITLE
Update .NET nanoFramework NuGets

### PR DESCRIPTION
**Pull request by nfbot**
Automated update from @nfbot.

### CODE REVIEW

**Comment by angularsen** [comment]
Yes, it helps with a reminder sometimes!

[Release UnitsNet/4.128.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.128.0)

**Comment by angularsen** [comment]
The build seems to fail on downloading and installing the nanoframework vsix install right now. Will retry it a bit later.

https://ci.appveyor.com/project/angularsen/unitsnet

image

**Comment by josesimoes** [comment]
Thanks! 😁

Seems that the VSIX server is down. We've been replacing it with an alternative source. I'll submit a PR for unitsnet.

**Comment by josesimoes** [comment]
@angularsen #1073 fixes the build issue.

**Pull request merged**
