### PR TITLE
adding barrels per minute and barrels per hour

### PR DESCRIPTION
**Pull request by tweet1992**
[bph -> m3ps reference](https://www.google.com/search?q=oil+barrel+per+hour+to+cubic+meter+per+second)

[bpm -> m3ps reference](https://www.google.com/search?q=oil+barrel+per+minute+to+cubic+meter+per+second)

### CODE REVIEW

**Comment by gojanpaolo** [comment]
@tweet1992 Great work! Thanks for contributing :+1:

**Comment by angularsen** [comment]
Thanks for reviewing @gojanpaolo !

**Comment by gojanpaolo** [comment]
You're welcome! :)

**Comment by tweet1992** [comment]
Thanks guys! Any idea when you will get an update to the nuget package out?

**Comment by gojanpaolo** [comment]
@angularsen Please let me know if we can release a new package? I should be able to have some time to do it this week :)

**Comment by angularsen** [comment]
@gojanpaolo Absolutely, please do. Generally I try to release a new version after every every PR or batch of PRs I merge, unless I'm waiting for something else to merge soon. I don't recall if you have released a package before, so please ask if anything is unclear. The steps are in the wiki.

**Pull request merged**
