### PR TITLE
Rename Flow To Volume Flow

### PR DESCRIPTION
**Pull request by gojanpaolo**
Fixes https://github.com/angularsen/UnitsNet/issues/363

### CODE REVIEW

**Comment by angularsen** [comment]
Looks good, I assume you did copied things over and renamed it so I didn't verify the conversion test values.

**Comment by gojanpaolo** [comment]
Yes I just copy/pasted from FlowTests. Thought about rearranging it but didn't to avoid extra manual checking. Thank you for closing!

**Comment by ferittuncer** [comment]
@gojanpaolo I know its kinda late, I had to come up with this earlier, but, shouldn't it be volumetric flow instead of volume flow?

We are developing a tool which can solve pipe networks and we always use the term volumetric flow and I never heard volume flow. My background is CS, so I don't have a deep knowledge about these thermodynamic context, so I may be wrong. Anyway, just wanted to ask if you considered this alternative.

**Comment by gojanpaolo** [comment]
I'm fine with either also. We can add VolumetricFlow and make VolumeFlow obsolete.

**Comment by ferittuncer** [comment]
If both terms are okay let's not create another obsolote and stick with VolumeFlow then.

**Comment by angularsen** [comment]
I second that!

**Pull request merged**
