### PR TITLE
Add 'SlugSquareFoot' and 'SlugSquareInch' as units of MassMomentOfIntertia, and 'slug' as a unit of Mass

### PR DESCRIPTION
**Pull request by McNeight**

### CODE REVIEW

**Comment by angularsen** [comment]
@McNeight Just a follow up, I'm waiting for your feedback on how to proceed here.

**Comment by angularsen** [comment]
@McNeight I don't mean to nag, but still waiting for you on this one. Only minor changes required to merge this.

**Comment by McNeight** [comment]
@angularsen I apologize for the delay, but I've made the changes you've requested.

For future reference, what are good sources for conversion constants, and how many significant digits do you prefer?

**Comment by angularsen** [comment]
Awesome!
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#quick-summary-of-steps

I addet a new bullet point to the list:
> For irrational (infinite) conversion factors, use 7 significant figures

Good sources are google and various conversion websites. I usually double check with two sources.

In the wiki there is an example on how to look up these factors.
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#4-fix-generated-test-stubs-to-resolve-compile-errors-tests

**Comment by angularsen** [comment]
I changed the working to
> For irrational (infinite) conversion factors, use as many as you can up to 12 significant figures

**Comment by angularsen** [comment]
Nuget on the way out
https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F3.106.0

**Comment by angularsen** [comment]
Released in [3.107.1](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F3.107.1).

**Pull request merged**
