### PR TITLE
Added UsQuart and UsPint volumes

### PR DESCRIPTION
**Pull request by CaptainBlueScreen**

### CODE REVIEW

**Comment by angularsen** [comment]
@gojanpaolo Got time to review this one? I can take a look this weekend at the earliest.

**Comment by gojanpaolo** [comment]
Sure. I can do it today. :)

**Comment by gojanpaolo** [comment]
@CaptainBlueScreen @angularsen Released v3.99 :)

**Comment by angularsen** [comment]
Awesome!

**Pull request merged**
