### PR TITLE
Feature: AmountOfSubstance

### PR DESCRIPTION
**Pull request by ferittuncer**

### CODE REVIEW

**Comment by ferittuncer** [comment]
We built successfully in our fork, don't know why it didn't build in AppVeyor. I'm going to investigate this issue as soon as possible.

**Comment by ferittuncer** [comment]
Any ideas how to deal with this error?

> [10/27/2017 11:49:04 AM Error] Testhost process exited with error: It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
>   - Check application dependencies and target a framework version installed at:
>       \
>   - Alternatively, install the framework version '1.1.2'.

Because of this I can't load all the tests.

**Comment by ferittuncer** [comment]
Installing [DotNetCore.1.0.5_1.1.2-WindowsHosting](https://go.microsoft.com/fwlink/?linkid=848766) solved the problem.

**Comment by ferittuncer** [comment]
#303

**Comment by angularsen** [comment]
Not sure why the build server doesn't like this, the changes look good to me. I'll investigate a bit.

My only feedback here is as mentioned in issue:
1. Should we add `PoundPerMole`?
2. Should it be named `AmountOfSubstance` or `SubstanceAmount`? I have a preference for `AmountOfSubstance`, because that is the exact wording used everywhere when I google it.

**Comment by angularsen** [comment]
Ok, figured it out. You need to merge in latest `origin/master` (or rebase on top of it) to get the newest code generation scripts. Your branch is based on the old scripts and you generated a file in the wrong location, and the build server will also regenerate the code when it simulates merging into `origin/master` to be doubly sure, and then it gets two of the same file.

**Comment by ferittuncer** [comment]
PoundPerMole is implemented in the other pull request. We don't use it in our project at the moment but I guess it can be useful for us or someone else later on. What do you prefer? To have it or not to have it?

I'm okay with both SubstanceAmount and AmountOfSubstrance. Reason I chose SubstanceAmount is source-code readability. 

As soon as you let me know your decision, I'll proceed.

**Comment by ferittuncer** [comment]
Oh @angularsen , did you mean `PoundMole` by saying `PoundPerMole`?

**Comment by angularsen** [comment]
Ah, yes PoundMole. I think it's good to add for consistency and completeness.

**Comment by angularsen** [comment]
Also, let's go with AmountOfSubstance then if you agree that also works well.

**Comment by ferittuncer** [comment]
I think it's ready. Can you please review?

**Comment by angularsen** [comment]
Perfect! Looks good.

**Pull request merged**
