### PR TITLE
Feature: MolarEntropy

### LINKED ISSUE #307: Proposal: MolarEntropy
We would like to implement `MolarEntropy` quantity according to these pages: 

- https://physics.nist.gov/cuu/Units/units.html

- https://en.wikipedia.org/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvU3RhbmRhcmRfbW9sYXJfZW50cm9weQ

### PR DESCRIPTION
**Pull request by ferittuncer**
Implemented MolarEntropy 
Fixes #307

### CODE REVIEW

**Comment by angularsen** [comment]
Need to resolve merge conflicts.

**Comment by ferittuncer** [comment]
Interesting, I didn't understand why this happened. Should I delete MolarEnergy parts and leave MolarEntropy parts?

**Comment by ferittuncer** [comment]
No, I think we should keep both of them. This happened because of last merged pull request.

**Comment by angularsen** [comment]
It happened because I merged two other pull requests, and there were now conflicting changes trying to merge this PR. Github automatically attempts to merge when `origin/master` changes to report whether it is ready to merge or not.

**Comment by angularsen** [comment]
I took a stab at fixing the merge conflict, github apparently has got a GUI to fix the conflict from within the pull request page. Neat!

**Pull request merged**
