### PR TITLE
Update nanoFramework dependencies

### PR DESCRIPTION
**Pull request by josesimoes**
- Fix bug in path when calling nuget CLI.
- Automatic update of all libraries with latest stable versions:
  + nanoFramework.CoreLibrary.1.11.7
  + nanoFramework.System.Math.1.4.3

### CODE REVIEW

**Comment by josesimoes** [comment]
@angularsen adding to this, is it possible to hide the "5.0-alpha" versions that are available on NuGet? Because that offers a higher version than the current one (4.x), in our automated update scripts, nuget is using those instead of the 4.x ones... completly screws this for our CI-CD... 😢

**Comment by angularsen** [comment]
Sorry for the delay, I thought I already merged this.

**Comment by angularsen** [comment]
@josesimoes Is version range an option for you?
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

I can hide the already published NF pre-release nugets if we need to, but we would also have to modify the scripts on v5 branch to not bump the NF nugets to avoid the problem on next deploy.

**Comment by josesimoes** [comment]
> Sorry for the delay, I thought I already merged this.

No problem! 😄

**Comment by josesimoes** [comment]
> @josesimoes Is version range an option for you? https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges
> 
> I can hide the already published NF pre-release nugets if we need to, but we would also have to modify the scripts on v5 branch to not bump the NF nugets to avoid the problem on next deploy.

Thanks for the pointer. Let me check if that works for us... not 100% sure because of the automation...

**Comment by josesimoes** [comment]
@angularsen the above doesn't work as we are relying on nuget CLI to find what to update and grab the version from the output. Still... I've tweaked our scripts so they only allow stable versions for UnitsNet, which does the trick and filters out the 5.0- alpha.

**Comment by angularsen** [comment]
Ok, great that you found a way to work around it 👏

**Comment by josesimoes** [comment]
@angularsen sorry to bother you again with this. It seems that the version being used it's the same as the previous one, so there was no package published to NuGet... can you please bump the version and rebuild?

**Comment by angularsen** [comment]
I just had the same thought 😅 

[Release UnitsNet/4.110.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.110.0)

**Pull request merged**
