### PR TITLE
New unit: Linear feet added as a new unit

### PR DESCRIPTION
**Pull request by Sonan1994**
Linear feet added as a new unit

### CODE REVIEW

**Comment by tmilnthorp** [comment]
A linear foot is no different than LengthUnit.Foot.

I don't want to dismiss this prematurely as being application specific, as the abbreviation (LF) is indeed different. Is this perhaps just an abbreviation we should add to allow ToString/Parse support?

**Comment by angularsen** [comment]
@Sonan1994 Any feedback on @tmilnthorp 's questions above?

**Comment by Sonan1994** [comment]
> @Sonan1994 Any feedback on @tmilnthorp 's questions above?

I am so sorry for the late response. Like @tmilnthorp said, it's just abbreviation :) Thank you, for the quick response. I am going to create new pull request where I add just new abbreviation.

**Comment by tmilnthorp** [comment]
No problem! I think that sounds good.

FYI parsing is easy, and when you do a ToString, I think length.ToString("a3") will work for you.

@angularsen I just thought - do we alphabetically sort abbreviations? We should not, and always add new ones to the end of the json file, and maintain that order. Otherwise ToString("a3") would be a behavior break.

**Comment by angularsen** [comment]
@tmilnthorp yes I was thinking the same thing, we should always append and I think that has been the practice except for in very rare cases removing abbreviations, which is a breaking change anyway.

**Comment by angularsen** [comment]
Closing this as the author would create a separate PR.

**Pull request closed without merging**
