### PR TITLE
Update .NET nanoFramework NuGets (v4)

### PR DESCRIPTION
**Pull request by angularsen**
Cherry picked #1177 to release/v4.

Automated update.

Co-authored-by: nanoframework@outlook.com <nfbot>
(cherry picked from commit 9e9d19efa220f4012f906ff7c8609b93987ec988)

### CODE REVIEW

**Comment by angularsen** [comment]
@josesimoes 
[Release UnitsNet/4.150.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.150.0)

**Comment by josesimoes** [comment]
Thank you very much!

**Comment by josesimoes** [comment]
@angularsen sorry to bother you with this, but the pipeline failed to push the nuget packages... seems that the push task failed because the "other" nuget packages are already in nuget.org with the same version.

On our pipelines we have the following option set so that when this happens it doesn't prevent the new ones from being published:
https://github.com/nanoframework/nf-tools/blob/25a8eec9f93be5b4daff38c31a83e913246d4754/azure-pipelines-templates/class-lib-publish.yml#L99

**Comment by angularsen** [comment]
Bleh. I forgot v4 branch still had this issue. I fixed it in master (v5) pipeline.

I did look into that config earlier, but `allowPackageConflicts: true` does not seem to have any effect for nuget.org. The docs also describe it only works for internal feeds hosted by DevOps. Maybe you always bump all versions at the same time?

The workaround I found was basically using `dotnet nuget push` CLI instead, which supports `--skip-duplicate`.

```yml
- task: Bash@3
  displayName: 'Push to nuget.org'
  env:
    NUGET_ORG_APIKEY: '$(NUGET_ORG_APIKEY)'
  inputs:
    targetType: 'inline'
    script: 'dotnet nuget push "*.nupkg" --skip-duplicate --api-key $(NUGET_ORG_APIKEY) --source https://api.nuget.org/v3/index.json'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
```

I pushed the fix to `release/v4` just now: 0608a27 - 💚 Skip duplicates when pushing nugets

Build is running: https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=276&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by angularsen** [comment]
@josesimoes No bother at all, thanks for letting me know.

I forgot v4 branch still had this issue. I fixed it in master (v5) pipeline.

I did look into that config earlier, but `allowPackageConflicts: true` does not seem to have any effect for nuget.org. The docs also describe it only works for internal feeds hosted by DevOps. Maybe you always bump all versions at the same time?

The workaround I found was basically using `dotnet nuget push` CLI instead, which supports `--skip-duplicate`.

```yml
- task: Bash@3
  displayName: 'Push to nuget.org'
  env:
    NUGET_ORG_APIKEY: '$(NUGET_ORG_APIKEY)'
  inputs:
    targetType: 'inline'
    script: 'dotnet nuget push "*.nupkg" --skip-duplicate --api-key $(NUGET_ORG_APIKEY) --source https://api.nuget.org/v3/index.json'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
```

I pushed the fix to `release/v4` just now: 0608a27 - 💚 Skip duplicates when pushing nugets

Build is running: https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=276&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by angularsen** [comment]
Having some issues, trying a few fixes.

**Comment by angularsen** [comment]
The nugets got pushed now.

**Comment by josesimoes** [comment]
OK please take a look at last part of my comment above. You have there the workaround we're using in nanoFramework. It's using nuget CLI so it works for any nuget package.

**Comment by josesimoes** [comment]
Thanks!! 🙂

**Comment by angularsen** [comment]
> OK please take a look at last part of my comment above. You have there the workaround we're using in nanoFramework. It's using nuget CLI so it works for any nuget package.

Ah, I read too quickly. Then I guess we both landed on the same workaround 👍

**Pull request merged**
