### PR TITLE
Update .NET nanoFramework NuGets

### PR DESCRIPTION
**Pull request by nfbot**
Automated update from @nfbot.

### CODE REVIEW

**Comment by angularsen** [comment]
@josesimoes Cool stuff. Is this ready to go or an experiment?

**Comment by josesimoes** [comment]
> @josesimoes Cool stuff. Is this ready to go or an experiment?

It's for real! Just added this automated update. Now it will run whenever a new version of mscorlib and/or math is published.
Please merge asap.

(that's why I noticed the missing restore step 😉  on my machine works fine... )

**Comment by angularsen** [comment]
I forget, do I also need to bump the nuget version?

**Comment by josesimoes** [comment]
> I forget, do I also need to bump the nuget version?

On UnitsNet? I guess so... you usually do that, don't you? Should I add that step to our script?

**Comment by josesimoes** [comment]
@angularsen if you could bump the version, that would be great!

**Comment by angularsen** [comment]
Done, 4.116.0.

You could run `./build/bump-version.sh minor` to bump it, but I would still have to manually tag the version so it is better for me to do it.

We could have CI control the versioning so that every build has an increasing version and it always publishes a new nuget, but I'm slightly concerned that we would start spitting out a lot more nuget versions than necessary. I'll think about it.

**Comment by angularsen** [comment]
[Release UnitsNet/4.116.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.116.0)

**Pull request merged**
