### PR TITLE
Added 30 new physical quantities; added 8 unit definitions to current physical quantities.

### PR DESCRIPTION
**Pull request by baxcoders**
Hello Andreas,
thank you for your excellent work, together with your collaborators.
We're a team of engineers operating on process automation software (among the other things).
Understanding and collecting measure units represent an important part of our job, thus we think we could help each other with this task.

In this our first PR we added some of the measure units we currently use. 
We followed your guide and we hope we've done everything fine.

Feel free to report any anomaly or required change.

Have a nice day.

_The BaxTeam_

Ps: Here's the list of all physical quantities and unit definitions added. 
We hope the number isn't too high to compute for a single PR! :)

_**New quantities (30)**_

**Altitude** - Base: MetersAboveSeaLevel (masl)
**ApparentEnergy** - Base: VoltamperesHour (VAh) + Prefixes: "Kilo", "Mega"
**AreaDensity** - Base: KilogramsPerMeterSquared (kg/m²)
**BitRate** - Base: BitPerSecond (bit/s, bps) + Prefixes: "Kilo", "Mega", "Giga", "Tera", "Peta", "Exa", "Kibi", "Mebi", "Gibi", "Tebi", "Pebi", "Exbi"
**BitRate** - Additional: BytePerSecond (B/s) + Prefixes: "Kilo", "Mega", "Giga", "Tera", "Peta", "Exa", "Kibi", "Mebi", "Gibi", "Tebi", "Pebi", "Exbi"
**Capacitance** - Base: Farad (F)
**ElectricCharge** - Base: Coulomb (C)
**ElectricChargeDensity** - Base: CoulombPerMeterCube (C/m³)
**ElectricConductance** - Base: Siemens (S) + Prefixes: "Milli", "Micro"  
**ElectricConductivity** - Base: SiemensPerMeter (S/m)
**ElectricCurrentDensity** - Base: AmperePerMeterSecondSquared (A/m²)
**ElectricCurrentGradient** - Base: AmperePerSecond (A/s)
**ElectricField** - Base: VoltPerMeter (V/m)
**ElectricInductance** - Base: Henry (H)
**ElectricResistivity** - Base: OhmMeter (Ω·m)
**Illuminance** - Base: Lux (lx)
**Irradiance** - Base: WattPerMeterSquared (W/m²) + Prefixes: "Kilo"
**Irradiation** - Base: JoulePerMeterSquared (J/m²)
**Irradiation** - Additional: WattHourPerMeterSquared (Wh/m²) + Prefixes: "Kilo"
**LuminousFlux** - Base: Lumen (lm)
**LuminousIntensity** - Base: Candela (cd)
**MagneticField** - Base: Tesla (T)
**MagneticFlux** - Base: Weber (Wb)
**Magnetization** - Base: AmperePerMeter (A/m)
**Permeability** - Base: HenryPerMeter (H/m)
**Permettivity** - Base: FaradPerMeter (F/m)
**PowerGradient** - Base: WattPerSecond(W/s) + Prefixes: "Kilo"
**Precipitation** - Base: MillimeterPerMinute (mm/min)
**ReactiveEnergy** - Base: VoltampereReactiveHour (varh) + Prefixes: "Kilo", "Mega"
**ReactivePowerGradient** - Base: VoltamperePerSecond (var/s) + Prefixes: "Kilo"
**SolidAngle** - Base: Steradian (sr)
**ThermalConductivity** - Base: WattPerMeterKelvin (W/m·K)
  
_**New UnitDefinitions (8)**_

**Angle** - Added unit: Revolution (r)
**ApparentPower** - Added prefix to base unit: "Giga"
**Density** - Added prefix to base unit: "Milli"
**Flow** - Added abbreviations: "l/s", "l/min", "l/h"
**MassFlow** - Added unit: TonPerHour (t/h)
**Power** - Added prefix to base unit: "Deci", "Deca"
**ReactivePower** - Added prefix to base unit: "Giga"
**RotationalAcceleration** - Added unit: RevolutionPerMinutePerSecond (rpm/s)

### CODE REVIEW

**Comment by ferittuncer** [comment]
Wow, a giant pull request : ) I think that it would be easier to review and merge if you would create a p.r. for each quantity, just my opinion.

**Comment by baxcoders** [comment]
Dear @ferittuncer,
thank you for your feedback.

If you think that 38 different PRs would help with the review process we will proceed this way.
Maybe we could "cluster" them in subsets (alphabetical order, semantic order etc), we accept suggestions.

**Comment by angularsen** [comment]
Wow! Awesome work.

I do side with @ferittuncer though, although a bit effort to do multiple
PRs I think ultimately we will be able to review it faster that way. We can
probably batch 5 quantities per PR to strike a balance, except those
quantities with a large number of units could probably have their own PRs.

I just changed "jobs" by starting at a new long-term client so I am quite
busy these days, but I can probably take a closer look this weekend. If you
could have the PRs ready by then, that would be would be great!

**Comment by baxcoders** [comment]
Ok then, we will follow your suggestions.

**Pull request closed without merging**
