### PR TITLE
Added implicit conversion from Scalar to double

### PR DESCRIPTION
**Pull request by cedricmoers**
- Added implicit conversion from Scalar to double
- Made exception for ScalarTestBase to ignore the Convert_ToBool_ThrowsInvalidCastException test for Scalar

### CODE REVIEW

**Comment by cedricmoers** [comment]
I also wonder if the implicit conversion from double to Scalar should also be implemented in a similar way:

`
        /// <summary>Defines an implicit conversion of a <see cref="Scalar"/> to a <see cref="double"/>.</summary>
        public static implicit operator double(Scalar scalar)
        {
            return scalar.Amount;
        }

        /// <summary>Defines an implicit conversion of a <see cref="double"/> to a <see cref="Scalar"/>.</summary>
        public static implicit operator Scalar(double value)
        {
            return Scalar.FromAmount(value);
        }

`

Also, should this mean that all arithmetic operations should be based on Scalar instead of Double? For example, if you divide a voltage by a voltage, would you then rather return a 'double', or a Scalar?

**Comment by cedricmoers** [comment]
In my scenario I use (and love) UnitsNet for scientific measurements. I have some value processing blocks that are by nature 'unit independent'. One of these blocks is for example a value processor that returns an average value of multiple measurements:

```
    public interface IValueProcessor
    {
        IQuantity Get(Func<IQuantity> quantities);
    }

    public class Average
    {
        public int Count { get; set; }
        IQuantity Get(Func<IQuantity> quantityProvider)
        {
            int count = Count;
            IQuantity sum = null;
            for (int i = 0; i < count; i++)
            {
                var q = quantityProvider();
                if (sum is null)
                    sum = q;
                else
                    sum = (dynamic)sum + q;
            }

            IQuantity avg = (dynamic)sum / count;

            return avg;
        }
    } 
```

The scalar is a big improvement here, since before the Scalar, I had to create a separate class for processors taking quantities and processors taking int/double/decimal, ... Before this, I had to use 'object' as the common class and check if the object was an IQuantity or a double/int/decimal. This became a bit ugly and I created a 'wrapper': IQuantifiable and some helper Structs. I never was happy with that and Scalar is likely to solve that.

Currently I see one (edge-)usecase that would benefit of returning the Scalar from arithmetic operations. Imagine I have a processor that does a Division on a given quantity that I do not know the type of:

```
    public class Divider
    {
        public IQuantity DivideBy { get; set; }
        IQuantity Get(Func<IQuantity> quantityProvider)
        {
            var q = quantityProvider();
            return (dynamic)q / DivideBy;
        }
    }
```

If the measured quantity is 5V and I want it divided by 2V, then the result I expect is 2.5 (no unit). Unfortunately, because the division in the ElectricPotential struct returns a 'double', which is not a Quantity, and thus the above will throw an InvalidCastException. If the division would return a Scalar, the above (I think) would work fine. 

If the expected result is in fact a double, then the implicit cast will do the correct casting for you.

Thus I see an advantage in returning a Scalar from arithmetics when normally a 'double' is returned, but I cannot oversee what the impact will be and how that will break the current system. I am willing to try this out.

**Comment by angularsen** [comment]
@cedricmoers Some more comments on Generic Math.
https://github.com/angularsen/UnitsNet/issues/780#issuecomment-958241530

**Comment by angularsen** [comment]
I'm sorry, what is the status of this PR again? 

It seems my last suggestion was
> I guess, if we can change all arithmetic method overloads to return Scalar, and provide implicit casts to double, then hopefully 🤞 all existing tests and people's application code will compile and run exactly as before?

Should we try changing all arithmetic methods retuning `double` to return `Scalar` instead? Or should we merge this PR as-is?

**Pull request closed without merging**
