### PR TITLE
Rename DecimalFraction units to Decimal

### PR DESCRIPTION
**Pull request by angularsen**
Decimal fraction is not a correct term.

> Definition of Decimal Fraction
> A fraction where the denominator (the bottom number) is a power of ten (such as 10, 100, 1000, etc).
[Source](https://www.mathsisfun.com/definitions/decimal-fraction.html).

> So, to convert a fraction to a decimal, divide the numerator by the denominator.
[Source](bbc.co.uk/bitesize/topics/znmtsbk/articles/z4ymtv4).

### Changes
- Add `Ratio.Decimal` unit, mark `DecimalFraction` unit as obsolete
- Add `RatioChangeRate.DecimalPerSecond`, mark `DecimalFractionPerSecond` unit as obsolete
- Change base unit of each quantity to the new unit

Changing the base unit should not be a breaking change for most users and the conversion precision is exactly the same as before for all units.

### CODE REVIEW

**Comment by angularsen** [comment]
Related to #879

**Comment by lipchev** [comment]
I'm not sure about this- the linked definition emphasizes the distinction between 1/2 (fraction) and 5/10 (decimal fraction). However what we're representing is the right hand side of the equation: e.g. 0.53 which is the [decimal](https://www.mathsisfun.com/decimal-fraction-percentage.html) _value representation_ of a fraction (i.e. using a decimal symbol).

**Comment by angularsen** [comment]
@lipchev Good point, some more googling and I believe _decimal_ is the correct term?

> So, to convert a fraction to a decimal, divide the numerator by the denominator.
https://www.bbc.co.uk/bitesize/topics/znmtsbk/articles/z4ymtv4

**Comment by angularsen** [comment]
Updated PR to use `Decimal` and updated both `Ratio` and `RatioChangeRate`.

**Comment by MarkCiliaVincenti** [comment]
The problem with Ratio.Decimal is that decimal is a type in C#, so it could create confusion.

**Comment by angularsen** [comment]
@MarkCiliaVincenti Right, but since its type is `double` I think maybe not a big problem.
After reading up on the terms I believe DecimalFraction is not a good choice either.

Are we happy with Decimal? Any other suggestions?
@lipchev @MarkCiliaVincenti

**Comment by lipchev** [comment]
I personally prefer `DecimalFraction` over `Decimal`: we're represents a `Ratio` in terms of a [Decimal Fraction](https://en.wikipedia.org/wiki/Decimal#Decimal_fractions) expressed (visually) using the 

> modern European decimal notation

I also think that renaming this would have quite a visible effect on client code (having obsolete warnings popping all over the place), that it simply wouldn't be worth the effort..

**Comment by angularsen** [comment]
@lipchev Ok, I had not considered the "visual representation" part. I guess it makes sense when reading the wiki section.

https://en.wikipedia.org/wiki/Decimal#Decimal_fractions

> The numbers that are represented by decimal numerals are the decimal fractions (sometimes called decimal numbers),
> For example, the numerals 
image
> represent the fractions 
image

I guess we _could_ call it `DecimalNumeral`, but that is a very unfamiliar term to me at least.
I agree, not worth the hassle. Let's stick with `DecimalFraction`.

**Pull request closed without merging**
