### PR TITLE
⚰️Remove checked-in tools requiring Git LFS

### PR DESCRIPTION
**Pull request by tmilnthorp**
GitHub currently charges $5 / month due to high bandwidth of downloading tools, of which most tools are not even used except NuGet.exe.

Also, checkout requires everyone to have Git LFS plugin installed.

### Changes
- Delete checked in Tools folder
- Download NuGet.exe in `init.ps1` script to new `.tools` folder
- Change `dotnet tool install` to use `.tools` folder
- Ignore `.tools` folder in Git
- Update init/build/clean scripts to use NuGet.exe in new location

### CODE REVIEW

**Comment by tmilnthorp** [comment]
Trying to remove all Git LFS files to remove the following error on build (or even checking out UnitsNet):
```
Cloning into './UnitsNet2'...
remote: Enumerating objects: 71476, done.
remote: Counting objects: 100% (23610/23610), done.
remote: Compressing objects: 100% (3957/3957), done.
remote: Total 71476 (delta 21266), reused 21395 (delta 19439), pack-reused 47866
Receiving objects: 100% (71476/71476), 57.81 MiB | 6.75 MiB/s, done.
Resolving deltas: 100% (63157/63157), done.
Updating files: 100% (1968/1968), done.
Downloading Tools/7-zip/7za.exe (536 KB)
Error downloading object: Tools/7-zip/7za.exe (fa252e5): Smudge error: Error downloading Tools/7-zip/7za.exe (fa252e501332b7486a972e7e471cf6915daa681af35c6aa102213921093eb2a3): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

The machines used by GitHub have [7Zip and NuGet preinstalled](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md).

(I don't know what sfk.exe is!)

**Comment by tmilnthorp** [comment]
> Thanks, I got the notification yesterday that the LFS _bandwidth_ of 1 GB was used up, 1.5 had been used. Storage was fine.
> 
> I guess the repo is being checked out a lot by CI systems, but I'm astonished that I'm hitting bandwidth limits on a fairly small projects with very small binary files.
> 
> I bought a LFS data pack to fix it short term, but I'm happy to remove the binaries we don't need.
> 
> I think we have some dependencies on nuget.exe at least. I don't think we can change the scripts to assume `nuget.exe` is in the PATH on all systems. Especially for those who check out the repo and run `build.bat` , it should "just work".
> 
> At my work, we use init scripts to download and install any dependencies required to build or run. Mostly Docker stuff. I'm thinking we can add an `init.bat` that downloads `Tools\nuget.exe` if it does not already exist? Same with any other dependencies we have, maybe 7zip.
> 
> We could also switch to GitHub actions, or my favorite Azure DevOps, but it's time I struggle to find. AppVeyor is excruciatingly slow at times.

Or better yet, dive into #693 and never worry about what's in a users path again 😉 

But I would definitely be in favor of moving to ADO or GitHub actions. I am familiar with ADO but not Actions.

**Comment by angularsen** [comment]
Oh yeah! Remote environment is really compelling. Have you tried it?

Still, I do think the init script is a good idea to make it real easy to checkout and build/run, as I would expect for any github project. Remote container is a nice supplement, but I wouldn't want to enforce it.

**Comment by angularsen** [comment]
I bought the LFS data pack, so we are good for at least 30 days, or until I unsubscribe.

**Comment by angularsen** [comment]
Well, if you ever feel like setting up a remote setup for UnitsNet, that would be really cool!

**Comment by tmilnthorp** [comment]
> Well, if you ever feel like setting up a remote setup for UnitsNet, that would be really cool!

I will try to find some time. Easier said than done though 😄

**Comment by angularsen** [comment]
Pushed some changes, think this is ready to go. Waiting for PR build to see that everything works.

Queued a CI build too: https://dev.azure.com/unitsnet/Units.NET/_build/results?buildId=541&view=results

**Pull request merged**
