### PR TITLE
Adding SourceLink properties and NuGet package

### PR DESCRIPTION
**Pull request by tmilnthorp**
Adding SourceLink per #532

### CODE REVIEW

**Comment by tmilnthorp** [comment]
I'm not 100% sure how this works so dunno how to test it :)

**Comment by angularsen** [comment]
Looks good to me, let's try it!

**Comment by angularsen** [comment]
@tmilnthorp I tried it and can't get it to work in Visual Studio 15.8.7, also running `sourcelink test` on it reveals some hashes don't match with the github URLs. Will need to look more into it.

Another thing I just realized; I don't think we can use SourceLink after we removed all the generated code - since that source code no longer exists on github. 😞 Maybe we should just stick to symbols nuget packages, which we already have.

**Comment by tmilnthorp** [comment]
Either that or we can add them back and use the following to clean up the GitHub diffs: https://robots.thoughtbot.com/github-diff-supression

This would be nice too so you don't have to rerun generate every time you check out, switch branches, etc.

**Comment by angularsen** [comment]
Let's continue discussion in #439.

**Comment by angularsen** [comment]
This was first reverted, then added back again in #548.

**Pull request merged**
