### PR TITLE
Add unit converter WPF sample app

### LINKED ISSUE #274: Request: Create demo unit converter app
I think it would be good to showcase a simple unit converter app to give a practical sample to link to, in particular to demonstrate #181.

* Create Winforms, WPF or UWP app in spirit of screenshot
* Update TODO in README about the example converter app

image

### PR DESCRIPTION
**Pull request by angularsen**
To illustrate how to enumerate quantities, units and to convert between them without hard coding any quantities.

image

The app lists all quantities (Length, Mass etc), and when you select one, it then lists all units for that quantity (if Length was chosen; meters, centimeters etc). Then it converts the numeric value from one selected unit to another.

This sample also highlights a limitation in the library that requires reflection in order to enumerate units for a selected quantity and to get the abbreviation for a unit, since the library does not provide a generic means to retrieve these without referencing types like `Length` and `LengthUnit` directly. There is definitely room for improvement in the library here, as previously discussed in #371 #354 #353 #308.

Fixes #274

### CODE REVIEW

**Comment by angularsen** [comment]
@eriove @ferittuncer @JKSnd for input. Also, this sample app pretty much sums up the current limitation of UnitsNet that currently requires reflection to do conversions without hard coded quantity types.

@YektaMirkanhi Since you asked about #354 Getting abbreviation list of a quantity 
@dayewah Since you made a sample app and have been doing this dance already, this may be of interest to you.

**Comment by gojanpaolo** [comment]
Need null checking here?
```
        public string FromHeader => $"Value [{SelectedFromUnit.Abbreviation}]";
        public string ToHeader => $"Result [{SelectedToUnit.Abbreviation}]";
```

**Comment by ferittuncer** [comment]
I just started to examine this sample. I got an exception just after a clicking to a quantity.

`NullPointerException` at line 85 in `MainWindowVm.cs`.

**Comment by angularsen** [comment]
Thanks for testing it, I've added the null checks. I was not able to reproduce this behavior so likely a racing condition.

**Comment by ferittuncer** [comment]
Working flawlessly now. 

I wonder why you didn't make result textbox editable like Google's converter.

**Comment by angularsen** [comment]
Ah, that was just me being lazy and trying to the the least amount of work :-)
I guess I just foresaw some issue with infinite cycles of one field change updating the other, which again updates the first one and so on. It's obviously solvable, I just avoided it the lazy bum that I am 😆

I'm merging in this since the bug is fixed. If anyone wants to improve this app that is awesome.

**Pull request merged**
