### PR TITLE
Replace PowerShell codegen with C#

### LINKED ISSUE #522: Look into alternatives to code generators
PowerShell works, but it's slow and the type system is very limited and can be challenging to work with compared to C#. For instance, parsing JSON into types for intellisense and sharing types between script files does not work very well in Visual Studio, VS Code or Rider.

This issue is just to have a place to dump ideas for improving the code generator, we will only make the jump if it makes considerable improvements over PowerShell.

### Geco
Simple code generator based on a console project, running on .Net core and using C# interpolated strings.
https://github.com/iQuarc/Geco

Pros: 
- It's C# - familiar and works with normal tooling
- Specifically made with code generation in mind
- Similar to T4 templates but supports debugging

### ~~ScriptCS~~ (out of favor due to poor tooling support)
Write C# apps with a text editor, nuget and the power of Roslyn! 
https://github.com/scriptcs/scriptcs

Pros:
- It's C# - familiar and works with normal tooling
- Run C# `.csx` files without any projects
- Entire C# and .NET at your disposal

Cons:
- Poor tooling support, intellisense and refactoring does not work well or at all
- Requires installing `ScriptCS` on developer PCs
- Not built-in way to emit generated text/code, but this could be as simple as `StringBuilder` and `File.WriteAllText`

### PR DESCRIPTION
**Pull request by angularsen**
Fixes #522 .

I've looked into some alternatives in #522 and found that plain old C# should do they job just nicely.
- [Microsoft's new & upcoming command line parser](https://github.com/dotnet/command-line-api)
- `dotnet run` support
- `dotnet-suggest` support  (experimental via DragonFruit package, but Summer Is Coming)
- Fast
- Easy to debug
- Strongly typed
- All your C# tools for intellisense, refactoring, code analysis etc works

The only downside I can think of is a slightly more cumbersome syntax, but it's really not much and tried to mitigate that with some helper methods.

### Changes
- Add new `/CodeGen` .NET Core 2.1 console app
- Remove old PowerShell scripts
- Update build scripts

The new codegen produces pretty much identical output, except for a few whitespace improvements.

See the README for more info.

### CODE REVIEW

**Comment by angularsen** [comment]
Updated the WRC scripts too.

**Comment by tmilnthorp** [comment]
Looks good to me! I'll have to pull the code and play with it when I get come time.

**Comment by angularsen** [comment]
Thanks, I'll merge this now and we can always refine it later.

**Comment by angularsen** [comment]
[Release UnitsNet/4.22.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.22.0)

**Pull request merged**
