### PR TITLE
Updated NuGet packages to latest stable

### PR DESCRIPTION
**Pull request by sequc82**
Prerelease versions skipped. All available stable updates included

### CODE REVIEW

**Comment by angularsen** [comment]
Huh! Seems like som test coverage failed.
https://ci.appveyor.com/project/angularsen/unitsnet/builds/29444674#L328

I can take a look later if you don't figure it out.

**Comment by sequc82** [comment]
That was unusual. It seems there is an SDK that the test projects are referencing that held .NET Core from updating with the rest of the NuGet packages. An update to the .csproj files and restoration of NuGet packages seems to have resolved the issue.

**Comment by sequc82** [comment]
@angularsen Well it looks like the tests passed, but there seems to be an issue with codecov. Any ideas?

https://ci.appveyor.com/project/angularsen/unitsnet/builds/29447339

**Comment by angularsen** [comment]
The codecov.io API seems to be a bit unstable, or perphaps the connection from the build agent. It doesn't happen very often, but sometimes it fails on this. I simply re-queued the build and it went through 😄

**Comment by angularsen** [comment]
Great stuff, thanks!

**Pull request merged**
