### PR TITLE
Add radiation equivalent dose rate

### PR DESCRIPTION
**Pull request by voronizer**
Add radiation equivalent [dose rate](https://en.wikipedia.org/wiki/Dose_rate).

### CODE REVIEW

**Comment by angularsen** [comment]
Thanks! I ported this to v6 branch also.
https://github.com/angularsen/UnitsNet/pull/1468

Nuget should be out shortly.
[Release UnitsNet/5.62.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.62.0)

**Comment by lipchev** [comment]
@angularsen 
Sorry, I'm perhaps a little late for the party, but I'd just like to point out that, IMO, the use of `Seconds` should be preferred to `Hours` for the `BaseUnit` definition, with the latter corresponding to the derived unit of time of SI. 

As it stands, the `RadiationEquivalentDose` would likely throw if asked for it's _official SI unit_ (i.e. using `ToUnit(UnitSystem.Si)`). We don't have any rules for _having a SI base unit_ (see #1463) but even if just as a performance consideration- given an operation (like the multiplication with `Duration`) that operates using the quantities `BaseUnit`s is significantly faster than one requiring a conversion to a non-base unit.

For example, multiplying some `RadiationEquivalentDose` by "30 minutes" would have the `Duration` perform a dual conversion from `Minutes` to `Seconds` and then from `Seconds` to `Hours`, which currently involves extra boxing of the `Enum`, in addition to asking the `ConcurrentDictionary`  of the `UnitConverter` for a custom conversion that _likely_ does not exist..

PS I love how the [build failed](https://app.codecov.io/gh/angularsen/UnitsNet/commit/36b783c6bec1113bfbe7628b60faf138b94a5511) due to the lack of coverage of the operator (_and the uncovered lines are finally showing up clearly_)- it's very useful in highlighting issues like the one I spotted just now.. 👍

**Comment by angularsen** [comment]
Gotcha, I was thinking about it, but didn't know if seconds made sense in this domain. A quick google reveals that there are conversions for Sievert/second, so sure, we can add that and set it as base unit I guess.

**Comment by angularsen** [comment]
https://github.com/angularsen/UnitsNet/pull/1469

**Comment by voronizer** [comment]
Sorry, I'm perhaps a little late for the party :), but. I'm working for the company related to measurement of radiation an I could say that the amount of Sieverts per seconds value could be too small even for Double unit - its just no sense. I don't know internals of UnitsNet deeply. I added Sv(rem) per hour as base unit widely used in industry and

**Comment by angularsen** [comment]
Not late at all, I'm just pushing too fast here, sorry my bad.

I did find references to Sievert/second, millisievert/second etc. so I assumed it would make sense to include it, mostly to have SI compatible units.
https://www.translatorscafe.com/unit-converter/en-US/radiation/21-27/sievert/second-milliroentgen/hour/
https://www.rp-alba.com/index.php?filename=radiationDoseRateConverter.php

I have no idea if these are reputable sources, but at least more than one source included it.

**Comment by voronizer** [comment]
Ok. Lets see how it will work. Thank you!

**Comment by angularsen** [comment]
Merged into V6 branch, nuget should be out shortly.

[Release UnitsNet/6.0.0-pre013 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F6.0.0-pre013)

**Pull request merged**
