### PR TITLE
Add Cell Density for cell counting

### PR DESCRIPTION
**Pull request by eugene-zhary**
Numerous procedures in biology and medicine require the counting of cells
The most commonly used units of measure for this purpose are cells/cm² and cells/mL

### CODE REVIEW

**Comment by angularsen** [comment]
Sorry, this is too domain specific.
There are extremely many variants of X units per volume, per area or per length. We can't add them all I'm afraid.

If it helps, there is ReciprocalArea, ReciprocalLength.

An issue describes adding `ReciprocalVolume` or `NumberDensity` for volume, would that help for you?
https://github.com/angularsen/UnitsNet/issues/1260

**Comment by eugene-zhary** [comment]
no problem 🥲

**Comment by eugene-zhary** [comment]
anyway, thank you for your suggestion!

**Comment by angularsen** [comment]
Thanks for taking it like a champ 🙌 

If you are looking to add more units later, it can be helpful to create an issue first and make sure it fits the library before you put in too much effort.

**Pull request closed without merging**
